#dubbo
dubbo:  application:    name: provider
  registry:    address: zookeeper://39.96.85.93:2181?backup=39.96.85.93:2181,39.96.85.93:2182,39.96.85.93:2183
    #check: false
  protocol:    name: dubbo
  scan:    base-packages:    - org.dubbo
  consumer:    check: false